version: "2"
services: 
  nginx:
    image: tutum/nginx
    ports:
      - "80"
    links:
      - phpfpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./nginx/nginx.conf:/etc/nginx/sites-enabled/default

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
  phpfpm:
    image: php:fpm
    ports:
      - "9000"
    volumes:
      - ./public:/var/www/html
  mysql:
    image: mariadb
    volumes:
      - ./data/mysql-databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wp_foundation_six
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "80"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      PMA_ARBITRARY: 1